In [15]:
import torch

X = torch.arange(42, dtype=torch.float).reshape(7,6)
print(X)
print(X.dtype)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.],
        [36., 37., 38., 39., 40., 41.]])
torch.float32


In [10]:
fc_layer = torch.nn.Linear(in_features=6,   # m = 6
                           out_features=3)  # b = 3

In [5]:
fc_layer.weight # should be equal to 6*3

Parameter containing:
tensor([[-0.0564,  0.0532, -0.2943, -0.0947,  0.2045,  0.1955],
        [ 0.0598,  0.2906,  0.0505, -0.3370,  0.2876,  0.1532],
        [-0.1450, -0.1516, -0.1789,  0.3409,  0.3760,  0.2691]],
       requires_grad=True)

In [6]:
fc_layer.bias # should be equal to number of outputs 3

Parameter containing:
tensor([-0.3986, -0.1878, -0.4041], requires_grad=True)

In [7]:
# Fully connected layer
# .size() is equilant to .shape

print("X dim: ", X.size())
print("X dim: ", X.shape)
print()
print("W dim: ", fc_layer.weight.size())
print("W dim: ", fc_layer.weight.shape)
print()
print("b dim: ", fc_layer.bias.size())
print("b dim: ", fc_layer.bias.shape)
print()

X dim:  torch.Size([7, 6])
X dim:  torch.Size([7, 6])

W dim:  torch.Size([3, 6])
W dim:  torch.Size([3, 6])

b dim:  torch.Size([3])
b dim:  torch.Size([3])



In [9]:
# X is your input tensor
# Apply the linear transfrmation 
linear_output = fc_layer(X)

# Linear_output : output tensor after the input tensor X has been passes through the linear layer
# matrix multiplication and addition of biases

print("Linear output: ", linear_output)


Linear output:  tensor([[ 0.5773,  1.1095,  2.9586],
        [ 0.6240,  4.1380,  6.0215],
        [ 0.6708,  7.1665,  9.0844],
        [ 0.7175, 10.1950, 12.1473],
        [ 0.7642, 13.2235, 15.2102],
        [ 0.8109, 16.2520, 18.2731],
        [ 0.8577, 19.2805, 21.3360]], grad_fn=<AddmmBackward0>)


In [18]:
import torch

# Check if CUDA (GPU support) is available
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")

# If CUDA is not available, it's likely because you're on a MacBook or other non-Nvidia GPU system
# PyTorch 1.12 and newer might support Apple Silicon (M1/M2) GPUs through Metal but that's a different setup

if cuda_available:
    # Print the number of GPUs available
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    
    # Print the name of the first GPU
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
else:
    print("No CUDA-compatible GPU found. Operations will run on the CPU.")


CUDA Available: False
No CUDA-compatible GPU found. Operations will run on the CPU.
