## Dot Product understanding

## This is for single neuron with 4 inputs and 4 weights and 1 bias 

In [3]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

# convert list to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)

#Calculate the dot product and add the bias
outputs = np.dot(weights_array, inputs_array) + bias

print(f"the output of the neuron is : {outputs}")

the output of the neuron is : 4.8


## LAYER OF NEURONS USING NUMPY

we will have 4 inputs for each neuron and 4 weights for each neuron and 3 neurons

In [9]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]


# Convert lists to numpy arrays
input_array = np.array(inputs)
weights_array = np.array(weights)
bias_array = np.array(biases)

# Calculate the output of the layer by doing dot product of the inputs and weights and adding the bias

layer_outputs = np.dot(weights_array, inputs_array) + bias_array

print(f"The output of the layer is : {layer_outputs}")


The output of the layer is : [4.8   1.21  2.385]


## LAYER OF NEURONS AND BATCH OF DATA USING NUMPY

Need to take the transpose of the weight matrix

the layer will have different inputs for each neuron with the different weights 


In [13]:
import numpy as np 

# Inputs 3* 4, Weights 3* 4, biases
inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Now we can not directly do the matrix multiplication so we will use transpose 

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

# Calculate the output of the layer 

layer_outputs = np.dot(inputs_array, weights_array.T) + biases_array

print(f"the layer output is :\n {layer_outputs}")

the layer output is :
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## 2 LAYERS AND BATCH OF DATA USING NUMPY

we will have multiple inputs and multiple weights and we will calculate for each layer

Note : outputs of the first layer will be the inputs of the 2nd layer along with the new weights and biases

In [27]:
import numpy as np 

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

#Convert the lists into arrays 
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases1_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the Layers output 
print(f"The shapes are :{inputs_array.shape, weights_array.shape}") # The dimensions are :((3, 4), (3, 4))
# Since the inner dimentions are not matching we should do transpose of any one of it 

layer1_outputs = np.dot(inputs_array, weights_array.T) + biases1_array
print(f"Layer1 outputs is : \n{layer1_outputs}")
print(f"for layer to shape checks : {layer1_outputs.shape, weights2_array.shape}")

The shapes are :((3, 4), (3, 4))
Layer1 outputs is : 
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
for layer to shape checks : ((3, 3), (3, 3))


In [29]:
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(f"Layer2 outputs is : \n{layer2_outputs}")

Layer2 outputs is : 
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
